repos:
  # Ruff linting and formatting.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      - id: ruff
        name: ruff check
        args: [ --fix ]
      - id: ruff-format
  # keep lockfile up-to-date
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.9
    hooks:
      - id: uv-lock
  # ty - type checking 
  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: uv run ty check
        language: python
