name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  # See: https://github.com/pre-commit/action
  lint:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: 
          - "3.12"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Pre-Commit
        uses: pre-commit/action@v3.0.1
